### ISSUE TITLE
fnt3-desc.js 404 (Not Found)

### ISSUE THREAD

**Issue by cesarmm** [metafloor/bwip-js#98]
Hi,
 when the browser load the scripts of bwip-js, at console, I've got the next error:

xhr-fonts.js:38 GET http://localhost:35759/Scripts/bwipjs/fonts/fnt3-desc.js 404 (Not Found)

I've looked the code and I've seen metrics(id) as a recursive function without any stop. It seems like a method to stop when and error is returned by the server.

```

	function metrics(id) {
		var xhr = new XMLHttpRequest;
		xhr.open('GET', bwipjs_fonts.fontdir + 'fnt' + id + '-desc.js', true);
		xhr.onreadystatechange = function () {
			if (xhr.status == 200 && xhr.readyState == 4) {
				try {
					eval(xhr.responseText);
					metrics(id+1);  <--- where is the limit to stop?

				} catch (e) {
					console.log(e);
				}
			}
		}
```

Sorry if I misunderstood the code or perhaps I've download a bad zip.

Thanks in advance.

**Comment by metafloor** [comment]
Not sure what version of the code you are running as I do not recognize that `if (...)` statement.  But the code works by only recursing when successful.  Therefore it will always go one to many on the id, then stop.

**Comment by smcauliffe** [comment]
I'm seeing this as well after a fresh clone and npm install.

**Comment by cesarmm** [comment]
You can see it at:
bwip-js/lib/xhr-fonts.js
line 29.

When it loads, begin to iterate and when fail stops. But the error is in the browser console.

**Comment by danylomarkov** [comment]
What's the status of this issue? It's still present in 1.6.3 version from npm.

**Comment by EmanuelaGr** [comment]
I have the same problem. There is a solution for this?

**Comment by metafloor** [comment]
It is just a normal warning message.  If it bothers you, comment it out.  Not sure how it got back into the code but it is harmless and will be removed on the next release.

**Comment by marr** [comment]
I symlinked the `fonts` directory and still see this error. The real issue is that the `includetext` option doesn't seem to show the text. Is that something related to loading of fonts (this ticket)?

**Comment by metafloor** [comment]
If you are seeing the console message - specifically about `fnt3-desc.js` - then bwip-js is finding the fonts.  If the message is about `fnt0-desc.js`, then the fonts are not being found.

Check the request log for your server and verify that:
1.  a request is made for the font descriptions and font files; and
2.  your server is returning the correct files.

**Comment by marr** [comment]
Yes the fn3-desc.js error is what I see. I do not see any text rendered on the image.

**Comment by metafloor** [comment]
You didn't answer my question about the request logs.  Are you seeing the requests for the font files?

**Comment by marr** [comment]
fnt0-desc.js is successful (200).
fnt1-desc.js is successful (200).
fnt2-desc.js is successful (200).
fnt3-desc.js is not found (404).
I am using the `pdf417` barcode type.

**Comment by metafloor** [comment]
Have you verified that the text is rendered using the online demo, available from the project's home page?

Please reply with with exact options/values you are using.

**Comment by marr** [comment]
The text is rendered on the online demo when I set the _Alt text_ to `This is PDF417`.  
Is that the same function that `includetext`.

**Comment by metafloor** [comment]
You didn't include the values you are using.  I can't understand the problem without them.

**Comment by marr** [comment]
`{
    bcid: 'pdf417',
    scale:       3, 
    height:      10, 
    includetext: true, 
    textxalign:  'center',
    text: 'test',
}`

**Comment by metafloor** [comment]
Just verified against the BWIPP online demo.  That usage is not supported.  You must use `alttext`.

**Comment by marr** [comment]
Thanks, verified `alttext` works. https://github.com/bwipp/postscriptbarcode/wiki/Options-Reference should probably be updated with a reference to `alttext`.

**Comment by terryburton** [comment]
> Thanks, verified alttext works. https://github.com/bwipp/postscriptbarcode/wiki/Options-Reference should probably be updated with a reference to alttext.

@marr Noted, thanks.

**Comment by metafloor** [comment]
I suspect you need to tell the builder/packager (whichever one you are using) to include the `public/` or `bwip-js/fonts/` directory as part of the app package.

**Comment by EmanuelaGr** [comment]
I'm using webpack and I think they are included because on my build folder I have a bwipjs-fonts folder.

**Comment by metafloor** [comment]
webpack modifies code.  You need to see what may have changed between the unmodified font loading code and after packaging.  Other than that, I really cannot help much more.  This issue has something to do with how the code has been packaged, and most likely not about bwip-js.

**Comment by MnemosyneMei** [comment]
Hi @marr , may I know how did you verified alttext? what datatype does it accepts?

**Comment by metafloor** [comment]
`alttext` is the human readable text you want displayed with the bar code.  Best to keep it ASCII right now.

**Comment by marr** [comment]
@metafloor do you have time to address the original issue here? Specifically the 404 on fnt3-desc.js. I would like to avoid logging a 404 if I don't need to.

**Comment by ionmike** [comment]
Still an issue. Can you interrupt recursive call on [this line](https://github.com/metafloor/bwip-js/blob/master/browser-fonts.js#L50) (as @EmanuelaGr mentioned)?

**Comment by metafloor** [comment]
This is now resolved.

**Comment by justcoder1** [comment]
@metafloor I have recently installed (using npm i bwip-angular2) and I am still getting the fnt3-desc.js 404 (Not Found) #98 error. I have copied the fonts directory from node_modules to the assets folder and renamed as instructed.  What am I doing wrong? Thanks

**Comment by metafloor** [comment]
Angular must be pulling in an old version of bwip-js.  The last reference I can find to the xhr font loading is from version 1.7. There should be a `VERSION` property on the bwipjs object.  Please check it via `console.log(bwipjs)`.

**Comment by justcoder1** [comment]
@metafloor  I can see in my package.json it is set to version 1.0.6 (which is what it says on the npm website).  Do I just need to unistall this and do npm i bwip-angular2@1.7? Thanks

**Comment by metafloor** [comment]
Current version is 3.1 (https://www.npmjs.com/package/bwip-js).  Is angular limiting the dependency to version 1?

**Comment by justcoder1** [comment]
I tried running the console.log(bwipjs) but this did not return anything.  Maybe the issue is that I have installed bwip-angular2 instead of bwip-js, should bwip-js work in Angular?

**Comment by metafloor** [comment]
Not sure where there is an angular specific fork of bwip-js.  I recommend using the main bwip-js repo and if you experience any issues with the angular stack (primarily the bundler), let me know.

**Comment by justcoder1** [comment]
@metafloor Thanks for your help, I have installed bwip-js and this has resolved the issue and seems to work fine in Angular if I just replicate the instructions from the REACT example. Thanks Again
